version: '3'

tasks:
  db-setup:
    cmds:
      - pg_lsclusters
      - sudo pg_ctlcluster 16 main start
      - sudo service postgresql restart

  clean:
    cmds:
      - rm -rf lodge/src/gen
  
  ts-rs-gen:
    dir: court/
    cmds:
      - cargo test export_bindings
      - mkdir -p ../lodge/src/gen/types
      - mv -v bindings/* ../lodge/src/gen/types
      - rm -d bindings
    sources:
      - models/mod.rs
    generates:
      - ../lodge/src/gen/types

  sass-gen:
    dir: lodge/
    cmds:
      - sass -I ./ src/sass/main.scss ./dist/sass.css

  gen:
    deps: 
      - ts-rs-gen
      - sass-gen

  ts-build:
    dir: lodge/
    deps:
      - gen
    cmds:
      - npm run build

  rs-build:
    dir: court/
    cmds:
      - cargo build

  build:
    cmds:
      - task: ts-build
      - task: rs-build

  run:
    dir: court
    deps:
      - build
    cmds:
      - cargo run