version: '3'

tasks:
  setup:
    cmds:
      - npm install grpc-tools

  gen:
    cmds:
      - grpc_tools_node_protoc --js_out=import_style=commonjs,binary:gen/ --grpc_out=grpc_js:./gen/ --proto_path=../court/prototash/ prototash.proto